name: CI for Vue App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: --cwd findwater-vue install