name: CI for Vue App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install, Build, Test
        working-directory: findwater-vue
        uses: borales/actions-yarn@v2.3.0
        with: 
          cmd: install